version: '3.4'

services:
  fastdeliveruu.api:
    image: ${DOCKER_REGISTRY-}fastdeliveruuapi
    build:
      context: .
      dockerfile: src/FastDeliveruu.Api/Dockerfile
    container_name: fastdeliveruu.api
    ports:
      - 5000:5000
      - 5001:5001

  fastdeliveruu.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: fastdeliveruu.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=super_secret_password_123
      - MSSQL_PID=Express
    volumes:
      - ./.containers/fastdeliveruu-db:/var/opt/mssql/data
    ports:
      - 1433:1433    

  fastdeliveruu.cache:
    image: redis:latest
    container_name: fastdeliveruu.cache
    restart: always
    ports:
      - 6379:6379
