# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  fastdeliveruuapi:
    image: fastdeliveruuapi
    build:
      context: .
      dockerfile: src/FastDeliveruu.Api/Dockerfile
    ports:
      - 5233:5233
